country = ['canada', 'usa', 'france', 'kenia', 'greece']
print(country)
print(sorted(country))
print(country)
print(sorted(country))
print(country)
country.reverse()
print(country)
country.reverse()
print(country)
country.sort()
print(country)
country.sort(reverse=True)
print(country)
